/*
* generated by Xtext
*/
package org.yazgel.hibernatedsl.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.yazgel.hibernatedsl.xtext.services.HibernateGrammarAccess;

public class HibernateParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HibernateGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.yazgel.hibernatedsl.xtext.parser.antlr.internal.InternalHibernateParser createParser(XtextTokenStream stream) {
		return new org.yazgel.hibernatedsl.xtext.parser.antlr.internal.InternalHibernateParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}
	
	public HibernateGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HibernateGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
