/*
* generated by Xtext
*/
package org.yazgel.hibernatedsl.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HibernateAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/yazgel/hibernatedsl/xtext/parser/antlr/internal/InternalHibernate.tokens");
	}
}
