/*
 * generated by Xtext
 */
package org.yazgel.jpql.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JPQLRuntimeModule extends org.yazgel.jpql.xtext.AbstractJPQLRuntimeModule {

}
