/*
* generated by Xtext
*/
package org.yazgel.jpql.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JPQLStandaloneSetup extends JPQLStandaloneSetupGenerated{

	public static void doSetup() {
		new JPQLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

