/*
 * generated by Xtext
 */
package org.yazgel.jpql.xtext.ui.contentassist

import org.yazgel.jpql.xtext.ui.contentassist.AbstractJPQLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class JPQLProposalProvider extends AbstractJPQLProposalProvider {
}
