/*
 * generated by Xtext
 */
package org.yazgel.hibernatedsl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HibernateUiModule extends org.yazgel.hibernatedsl.xtext.ui.AbstractHibernateUiModule {
	public HibernateUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
