/*
 * generated by Xtext
 */
package org.yazgel.hibernatedsl.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.yazgel.hibernatedsl.xtext.ui.internal.HibernateActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HibernateExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HibernateActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HibernateActivator.getInstance().getInjector(HibernateActivator.ORG_YAZGEL_HIBERNATEDSL_XTEXT_HIBERNATE);
	}
	
}
