/*
 * generated by Xtext
 */
package org.yazgel.jpql.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractJPQLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.yazgel.jpql.xtext.jPQL.JPQLPackage.eINSTANCE);
		return result;
	}
}
