/*
 * generated by Xtext
 */
package org.yazgel.jpql.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JPQLUiModule extends org.yazgel.jpql.xtext.ui.AbstractJPQLUiModule {
	public JPQLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
