/*
 * generated by Xtext
 */
package org.yazgel.hibernatedsl.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HibernateRuntimeModule extends org.yazgel.hibernatedsl.xtext.AbstractHibernateRuntimeModule {

}
