/*
* generated by Xtext
*/
package org.yazgel.jpql.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JPQLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/yazgel/jpql/xtext/parser/antlr/internal/InternalJPQL.tokens");
	}
}
