/*
 * generated by Xtext
 */
package org.yazgel.hibernatedsl.xtext.ui.contentassist

import org.yazgel.hibernatedsl.xtext.ui.contentassist.AbstractHibernateProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HibernateProposalProvider extends AbstractHibernateProposalProvider {
}
